[".config/nvim"]
#  type = "git-repo"
    type = "archive"
#  url = "https://github.com/NvChad/NvChad.git"
    url = "https://github.com/NvChad/NvChad/archive/refs/heads/main.zip"
    refreshPeriod = "168h"
    stripComponents = 1

[".config/base16-shell"]
    type = "archive"
    url = "https://github.com/chriskempson/base16-shell/archive/refs/heads/master.zip"
    stripComponents = 1

[".config/vifm/colors/gruvbox.vifm"]
    type = "file"
    url = "https://raw.githubusercontent.com/vifm/vifm-colors/master/gruvbox.vifm"

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".config/tmux/tmux-statusline-gruvbox-dark.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/gseidler/tmux-statusline-gruvbox-dark/master/tmux-statusline-gruvbox-dark.conf"
