[".config/base16-shell"]
    type = "archive"
    url = "https://github.com/chriskempson/base16-shell/archive/refs/heads/master.zip"
    stripComponents = 1

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
