
[".config/vifm/colors/gruvbox.vifm"]
    type = "file"
    url = "https://raw.githubusercontent.com/vifm/vifm-colors/master/gruvbox.vifm"

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".config/tmux/tmux-statusline-gruvbox-dark.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/gseidler/tmux-statusline-gruvbox-dark/master/tmux-statusline-gruvbox-dark.conf"

[".config/vale/proselint"]
    type = "archive"
    url = "https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip"
    stripComponents = 1

[".config/vale/alex"]
    type = "archive"
    url = "https://github.com/errata-ai/alex/releases/latest/download/alex.zip"
    stripComponents = 1

[".config/vale/write-good"]
    type = "archive"
    url = "https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip"
    stripComponents = 1

[".local/bin/tea"]
    type = "file"
    # 0.9.0
    url = "https://gitea.com/attachments/c15910d0-736c-4dc3-846b-6440ad2048fd"
    executable = true
