[".local/share/lunarvim/lvim"]
    type = "git-repo"
    url = "https://github.com/LunarVim/LunarVim.git"

        [".local/share/lunarvim/lvim".clone]
        args = [ "--depth", "1" ]

        [".local/share/lunarvim/lvim".pull]
        args = [ "--dry-run" ]

[".config/bat/themes"]
  type = "archive"
  url = "https://github.com/catppuccin/bat/archive/refs/heads/main.zip"
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/*.tmTheme"]

[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".config/vale/proselint"]
    type = "archive"
    url = "https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip"
    stripComponents = 1

[".config/vale/alex"]
    type = "archive"
    url = "https://github.com/errata-ai/alex/releases/latest/download/alex.zip"
    stripComponents = 1

[".config/vale/write-good"]
    type = "archive"
    url = "https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip"
    stripComponents = 1

[".config/k9s/skin.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/k9s/main/dist/frappe.yml"
    refreshPeriod = "168h"
