#!/usr/bin/env zsh

if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

source $HOME/.zsh/init.zsh
source $HOME/.zsh/exports.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/stack.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/sdkman.zsh

if [ -f "$HOME/.zsh_plugins.sh" ]; then
  source $HOME/.zsh_plugins.sh
else
  echo "Bundling zsh plugins..."
  antibody bundle <$HOME/.zsh/plugins.txt >$HOME/.zsh_plugins.sh
  source $HOME/.zsh_plugins.sh
fi

eval "$(direnv hook zsh)"

# Load fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(starship init zsh)"
