{{- $refreshPeriod := "168h" }}

[_chezmoi]
  type = "file"
  url = 'https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi.zsh'
  refreshPeriod = "{{ $refreshPeriod }}"
[_exa]
  type = "file"
  url = 'https://raw.githubusercontent.com/ogham/exa/master/completions/zsh/_exa'
  refreshPeriod = "{{ $refreshPeriod }}"
