#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = "nerdtree"
    enable_filetree_gitstatus = true
    enable_filetree_gitstatus = true
    filetree_direction = "left"
    filemanager = "coc-explorer"
    # enable_javacomplete2_py = 1
    # enable_ycm = true
    autocomplete_method = "coc"
    enable_vimfiler_gitstatus = true
    enable_os_fileformat_icon = true
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    # autocomplete_method = "coc"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
    name = 'lang#html'

[[layers]]
    name = 'lang#java'

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = "lang#sh"

[[layers]]
    name = 'lang#toml'

[[layers]]
    name = "lang#typescript"

[[layers]]
    name = 'git'

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = 'ui'

[[layers]]
    name = 'fuzzy'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'
    git-plugin = "fugitive"

[[layers]]
    name = 'tools'

[[layers]]
    name = "treesitter"

[[layers]]
    name = "checkers"
    show_cursor_error = false
    enable = false

[[layers]]
    name = "gtags"
    gtagslabel = "ctags"

[[layers]]
    name = "lsp"
    filetypes = [
        "java" # Install: eclipse-jdt (https://github.com/eclipse/eclipse.jdt.ls)
    ]

[layers.override_cmd]
    java = [
        "java",
        "-Declipse.application=org.eclipse.jdt.ls.core.id1",
        "-Dosgi.bundles.defaultStartLevel=4",
        "-Declipse.product=org.eclipse.jdt.ls.core.product",
        "-Dlog.protocol=true",
        "-Dlog.level=DEBUG",
        "-noverify",
        "-Xmx4256m",
        "-jar",
        "/Users/lars/.bin/eclipse-jdt/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
        "-configuration",
        "/Users/lars/.bin/eclipse-jdt/config_mac",
        "-data",
        "/Users/lars/.bin/eclipse-jdt/data"
    ]

[[custom_plugins]]
    name = 'https://gitlab.com/code-stats/code-stats-vim.git'

[[custom_plugins]]
    name = 'ryanoasis/vim-devicons'

[[custom_plugins]]
    name = "yuki-ycino/fzf-preview.vim"

# [[custom_plugins]]
    # repo = "separatorbirshrestha/vim-lsp"
    # merged = 0
