plugin:
  # dive image layers
  dive:
    shortCut: d
    confirm: false
    description: Dive image
    scopes:
      - containers
    command: dive
    background: false
    args:
      - $COL-IMAGE
  # view resource logs using stern
  stern:
    shortCut: Ctrl-L
    confirm: false
    description: Logs <Stern>
    scopes:
      - pods
    command: stern
    background: false
    args:
      - --tail
      - 50
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  # view user-supplied values when the helm chart was created
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
      - helm
    command: sh
    background: false
    args:
      - -c
      - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less"
  images:
    shortCut: Shift-I
    confirm: false
    description: get images
    scopes:
      - pods
    command: kubectl
    background: false
    args:
      - images
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
