set nocompatible                " must be first line
set background=dark

" nvim support
if !has('nvim')
" Make arrow and other keys work
  set term=$TERM
endif

" highlight current line
"set cursorline

set backspace=indent,eol,start  " backspace for dummies
set linespace=0                 " No extra spaces between rows
set number                      " Line numbers on
set showmatch                   " show matching brackets/parenthesis
set incsearch                   " find as you type search
set hlsearch                    " highlight search terms

" Search is NOT case sensitive when the searched text is all lowercase
" Search becomes case sensitive when at least an uppercase letter is present
set ignorecase
set smartcase

set smartindent                 " for indentation
set shiftwidth=4                " use indents of 4 spaces
set expandtab                   " tabs are spaces, not tabs
set tabstop=4                   " an indentation every four columns
set softtabstop=4               " let backspace delete indent

set ttyfast

set hidden                      " A buffer becomes hidden when it is abandoned

set mouse=a                     " Enable mouse scroll wheel

set signcolumn=yes              "Display the signcolumn (leftmost column with gutters & errs...)

"Show hidden characters
" set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
" set listchars=tab:>-,trail:-
" set listchars=tab:»·
set listchars=tab:··
set list

" Make the Search Wrap message EXPLICIT Again!
" I.e.: "Search hit BOTTOM, continuing at TOP"
set shortmess+=S

"" Alternate screen (when backgrounding vim)
" set t_ti= t_te=

"set previewwindow

"  "set wildmenu" enables a menu at the bottom of the vim/gvim window.
"  The meaning of "list:longest,full" is so that when you do completion in the
"  command line via tab, these events will happen:
"  1. (on the first tab) a list of completions will be shown and the command will
"  be completed to the longest common command.
"  2. (on second tab) the wildmenu will show up with all the completions that were
"  listed before.
"  To test it out, type ":spe" and then hit tab once to see 1 and hit tab again
"  to see 2.
set wildmenu
set wildmode=list:longest,full

"Always show a bottom status line
set laststatus=2

" Padding lines b/w cursor line and top / bottom of the window
set scrolloff=5

" Make switching back to Normal mode (using ESC) fast.
" 'ttimeoutlen': time in ms to wait for a key code sequence to complete
"
set ttimeoutlen=50

" Make the timeout to disambiguate b/w a start of a command and a mapped
" sequence shorter.
" E.g. after pressin '/' once, I don't want to wait the default timeout of 1s
" before doing a search
" - / => search
" - // => nohlsearch
" 'timeoutlen': Time in milliseconds to wait for a mapped sequence to complete.
set timeoutlen=250

" Do not delete % when joining lines starting with %
set formatoptions-=j

set diffopt+=vertical

"" Global tags
set tags+=tags,.tags

"" Leader key
"let mapleader="'"
let mapleader = ","

" netrw show tree mode
let g:netrw_liststyle = 3

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" Plug plugins manager
"
call plug#begin(stdpath('data') . '/plugged')

Plug 'gruvbox-community/gruvbox'

" start screen
Plug 'mhinz/vim-startify'

" status line
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" git <3
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'

Plug 'preservim/nerdcommenter'
Plug 'preservim/nerdtree'
Plug 'preservim/tagbar'
Plug 'tpope/vim-eunuch'
Plug 'airblade/vim-rooter'
Plug 'editorconfig/editorconfig-vim'
Plug 'airblade/vim-gitgutter'
Plug 'Yggdroot/indentLine'

Plug 'ryanoasis/vim-devicons'

"Plug 'neoclide/coc.nvim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" fuzzy finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

" treesitter
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

Plug 'https://gitlab.com/code-stats/code-stats-vim.git'

"All of your Plugins must be added before the following line
call plug#end()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" Configs

colorscheme gruvbox
set background=dark
set termguicolors

" buffer switching
nnoremap gt :bnext<CR>
nnoremap gT :bprevious<CR>
nnoremap <C-S-Right> :bnext<CR>
nnoremap <C-S-Left> :bprevious<CR>
" new buffer
nnoremap <Leader>bn :enew<cr>
" close buffer
nnoremap <Leader>bq :bp <bar> bd! #<cr>
" close all buffers
nnoremap <Leader>bQ :bufdo bd! #<cr>
" list buffers
nnoremap <silent> <space>b :<C-u>Buffers<cr>

source $HOME/.vim/configs/airline.vim

source $HOME/.vim/configs/fzf.vim

source $HOME/.vim/configs/tagbar.vim

source $HOME/.vim/configs/nerdtree.vim

source $HOME/.vim/configs/coc.vim
