#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

# variables

padding=08
gap=06

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# default management type for yabai on startup
yabai -m config layout bsp

# new window spawns to the right if vertical, or bottom if horizontal split
yabai -m config window_placement second_child

# set all padding and gaps (default: 0)
yabai -m config top_padding     "$padding"
yabai -m config bottom_padding  "$padding"
yabai -m config left_padding    "$padding"
yabai -m config right_padding   "$padding"
yabai -m config window_gap      "$gap"

# border settings
yabai -m config window_border                   on
yabai -m config window_border_width             3
yabai -m config active_window_border_color      0xff46d9ff
yabai -m config normal_window_border_color      0xff9d91bb
yabai -m config insert_feedback_color           0xffd75f5f

# on or off (default: off)
yabai -m config auto_balance off

# floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.50

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set mouse drop action to swap or stack windows
yabai -m config mouse_drop_action stack

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# specify which display a newly created window should be managed in (default: default)
yabai -m config window_origin_display cursor

# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow float

# window opacity (default: off)
yabai -m config window_opacity          on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity   0.99
yabai -m config normal_window_opacity   0.90

# label spaces and assign apps
yabai -m space 1 --label "web"
yabai -m rule --add app="^Firefox$" title!="^Mozilla Firefox" space="web"
yabai -m rule --add app="^Tor*" space="web"
yabai -m rule --add app="^Chromium*" space="web"
yabai -m rule --add app="^Safari*" space="web"
yabai -m rule --add app="^Brave*" space="web"

yabai -m space 2 --label "code"

yabai -m space 3 --label "productivity"

yabai -m space 4 --label "communication"

yabai -m space 5 --label "reference"

yabai -m space 6 --label "utility"

yabai -m space 7 --label "media"
yabai -m rule --add app="^Spotify$" space="media"

yabai -m space 10 --label "misc"

# application excpetions
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Bartender 4$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off border=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Rancher Desktop$" manage=off

echo "yabai configuration loaded.."
