#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

# variables

padding=08
gap=06

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child

yabai -m config window_topmost off

yabai -m config window_shadow on
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 0.99
yabai -m config normal_window_opacity 0.90

yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xff46d9ff
yabai -m config normal_window_border_color 0xff9d91bb
yabai -m config insert_feedback_color 0xffd75f5f

yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding "$padding"
yabai -m config bottom_padding "$padding"
yabai -m config left_padding "$padding"
yabai -m config right_padding "$padding"
yabai -m config window_gap "$gap"

# space names
yabai -m space 1 --label "org"
yabai -m space 2 --label "www"
yabai -m space 3 --label "dev"
yabai -m space 4 --label "mail"
yabai -m space 5 --label "5-chat"
yabai -m space 6 --label "conf"
yabai -m space 7 --label "read"
yabai -m space 8 --label "music"
yabai -m space 9 --label "9"

# space 1: terminal

# space 2: coding

# space 3: browser

# application excpetions
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Bartender 4$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off border=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Rancher Desktop$" manage=off

yabai -m rule --add app="^Spotify$" space=8

echo "yabai configuration loaded.."
